### ISSUE TITLE
Debuffs delay to show up and refresh after the new update

### ISSUE THREAD

**Issue by 3majed** [bkader/PlateBuffs_WoTLK#2]
Thanks Kader for the great work you are doing for WOTLK community. The days of red question marks on the nameplates are gone with this backporting All thanks to you.

As the title says, just downloaded the new update with the new commits and found out that debuffs show up very late (4~5 seconds late) and sometimes don't refresh (takes the same amount to refresh around 4~5 seconds), so I went back to the old version (before the new commits) and the issue is gone. Hope I helped with this information and again thanks for your work.

**Comment by MaelKoT** [comment]
ye, before commit 4fd4a22 all works good, but after...

**Comment by bkader** [comment]
I don't know why this issues happens but, I removed everything related to ElvUI and updated the libraries used.
I noticed a slight delay and sometimes they don't even show, after removing what was added, updating libraries and fixes few issues it worked fine. Can you please update and try it to see? @3majed

**Comment by 3majed** [comment]
@bkader , Just tested after the update, working fine.

**Comment by 3majed** [comment]
> @bkader , Just tested after the update, working fine.

found a small issue, if you move the camera kinda fast it will disappear for a second and show up again. I may have to clip this to make to show it

**Comment by bkader** [comment]
@3majed .. There are limitations for what we can do with **Nameplates** in this expansion. Unless the person is trolling, in panic, having a seizure or a stroke, no one will be moving the camera like that.

**Comment by 3majed** [comment]
> @3majed .. There are limitations for what we can do with **Nameplates** in this expansion. Unless the person is trolling, in panic, having a seizure or a stroke, no one will be moving the camera like that.

Ya true, thought it may happen in other situations but so far all good, tested it in few characters in BGs+RDFs and all working as how it was before. Thanks for the fix
