### ISSUE TITLE
PlateBuffs isn't working after the last update

### ISSUE THREAD

**Issue by SorenMills** [bkader/PlateBuffs_WoTLK#4]
downloaded the updated version a week ago and the mess started , buffs only shown like 10% of a time, They keep glitching , disappearing from the plate all the time. Is there a way a can download the previous version before that "libnamplate10" update ???

**Comment by bkader** [comment]
Hello @SorenMills and sorry for my late reply.
I don't know why it's not working properly after the lib was updated, I really have nameplates when it comes to wotlk expansion.
You can always download the files from any previous commit, [here is the last one](https://github.com/bkader/PlateBuffs_WoTLK/tree/04d9af92c824d08b305cb88d3e0f734ca928c892) before updating the lib. Meanwhile, I will take a look at what's causing the problem.
